### ISSUE TITLE
One more trial in creating issue

### ISSUE THREAD

**Issue by ykpkilic61** [eu3-user/JDBC_Project#83]
I try to label it with "bug", but cannot do it man!! **Kamoon** 
@eu3-user 
@ALIYILD 🥇 #12

**Comment by ALIYILD** [comment]
Hey boyyyyyy It is not a bug... You fireddddddd....

**Comment by ykpkilic61** [comment]
👯‍♂️ thanks for firing me 👍

**Comment by SuleymanTaner** [comment]
guys what are you. doing here?

**Comment by ALIYILD** [comment]
🤼
